### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by steppenwolf212** [jehutyDev/akumoe-downloader#1]

**Comment by jehutyDev** [comment]
I'm sorry for the very late answer, I've just tested the script and it worked fine, it seems to me like (if it was the case) on multiple or constant downloads the server it redirected your connection requests and the 4kb images  where just placeholder files, I'll bet that after a couple hours it would return to normal behavior.

Again, sorry for the late answer, I just did this on my free time and wanted to share it.
